ALTER TABLE events ADD COLUMN IF NOT EXISTS organization_name TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS website_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS twitter_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS discord_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS max_participants INTEGER;
